import {
  ArrowDown,
  ArrowUp,
  CircleAlert,
  Info,
  Minus,
  Sparkles,
  TriangleAlert,
} from "lucide-react";

import type { Basis, Obligation, Priority, Severity } from "../../api/types";
import { Badge, type Tone } from "../../components/ui/Badge";

const OBLIGATION: Record<
  Obligation,
  { label: string; tone: Tone; variant: "soft" | "outline"; title: string }
> = {
  mandatory: {
    label: "Mandatory",
    tone: "info",
    variant: "soft",
    title: "Normative: shall / must",
  },
  recommended: {
    label: "Recommended",
    tone: "info",
    variant: "outline",
    title: "Advisory: should",
  },
  permitted: { label: "Permitted", tone: "neutral", variant: "outline", title: "Permissive: may" },
  informational: {
    label: "Informational",
    tone: "neutral",
    variant: "soft",
    title: "No normative wording",
  },
};

export function ObligationBadge({ obligation }: { obligation: Obligation }) {
  const meta = OBLIGATION[obligation];
  return (
    <Badge tone={meta.tone} variant={meta.variant} title={meta.title}>
      {meta.label}
    </Badge>
  );
}

export const INFERRED_TOOLTIP = "Inferred by AI — not stated verbatim in the document";

/** "Explicit" (stated in the document) or a dashed "Inferred" tag. */
export function BasisTag({ basis }: { basis: Basis }) {
  if (basis === "inferred") {
    return (
      <Badge tone="ai" variant="dashed" title={INFERRED_TOOLTIP}>
        Inferred
      </Badge>
    );
  }
  return (
    <Badge tone="neutral" title="Stated in the document">
      Explicit
    </Badge>
  );
}

const SEVERITY: Record<Severity, { label: string; tone: Tone; Icon: typeof Info }> = {
  high: { label: "High", tone: "danger", Icon: CircleAlert },
  medium: { label: "Medium", tone: "warning", Icon: TriangleAlert },
  low: { label: "Low", tone: "neutral", Icon: Info },
};

export function SeverityBadge({ severity }: { severity: Severity }) {
  const { label, tone, Icon } = SEVERITY[severity];
  return (
    <Badge tone={tone} icon={<Icon />} title={`Severity: ${label}`}>
      {label}
    </Badge>
  );
}

const PRIORITY: Record<Priority, { label: string; tone: Tone; Icon: typeof Info }> = {
  high: { label: "High priority", tone: "danger", Icon: ArrowUp },
  medium: { label: "Medium priority", tone: "warning", Icon: Minus },
  low: { label: "Low priority", tone: "neutral", Icon: ArrowDown },
};

export function PriorityBadge({ priority }: { priority: Priority }) {
  const { label, tone, Icon } = PRIORITY[priority];
  return (
    <Badge tone={tone} variant="outline" icon={<Icon />}>
      {label}
    </Badge>
  );
}

/** Violet "AI-generated" label, used sparingly. */
export function AiGeneratedTag() {
  return (
    <Badge tone="ai" icon={<Sparkles />} title="Generated by an AI model from the document text">
      AI-generated
    </Badge>
  );
}

export const SEVERITY_ORDER: Record<Severity, number> = { high: 0, medium: 1, low: 2 };
export const PRIORITY_ORDER: Record<Priority, number> = { high: 0, medium: 1, low: 2 };
