"""DEVELOPMENT ONLY fake LLM provider.

Produces deterministic, schema-valid output from simple keyword heuristics over the document text,
so the UI and end-to-end tests can run offline without an AI service. It performs no real
analysis and must never be used for it — the provider is flagged ``development_only`` and says
so in every report's limitations.

Input conventions (tolerant): the document context contains ``<page number="N" ...>text</page>``
elements (attributes such as ``status="no-text"`` are allowed, basic XML entities are decoded);
for the "ask" task the question is inside ``<question>...</question>`` in the instruction.
Every quote is an exact substring of the page text it cites, so citation verification passes.
"""

from __future__ import annotations

import bisect
import re
import time
from dataclasses import dataclass, field
from typing import TypeVar

from pydantic import BaseModel

from docintel.core.errors import AIRequestRejectedError
from docintel.providers.llm.base import LLMProvider, LLMRequest, LLMResponse, LLMUsage
from docintel.schemas.report import (
    LLMAction,
    LLMAnswerOutput,
    LLMExecutiveSummary,
    LLMKeyPoint,
    LLMRequirement,
    LLMRequirementsOutput,
    LLMRisk,
    LLMRisksOutput,
    LLMSpecification,
    LLMSummarizeOutput,
    LLMSummary,
    Obligation,
    Severity,
    SourceQuote,
)

#: Maximum number of items per list in the generated output.
MAX_ITEMS = 10
_MIN_QUOTE_WORDS = 5
_MAX_QUOTE_WORDS = 25
_MAX_KEY_POINTS = 5

_DEV_LIMITATION = (
    "Generated by the development-only fake AI provider from keyword heuristics; "
    "this is not a real analysis."
)

# --- Input parsing ---------------------------------------------------------------------------

_PAGE_RE = re.compile(
    r"<page\b(?P<attrs>[^>]*?)(?:/>|>(?P<body>.*?)</page\s*>)", re.DOTALL | re.IGNORECASE
)
_ATTR_RE = re.compile(r"""([\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>/]+))""")
_QUESTION_RE = re.compile(r"<question\b[^>]*>(?P<q>.*?)</question\s*>", re.DOTALL | re.IGNORECASE)
_TAG_RE = re.compile(r"<[^>]+>")
_NO_TEXT_STATUSES = {"no-text", "empty", "needs-ocr"}
_ENTITIES = (("&lt;", "<"), ("&gt;", ">"), ("&quot;", '"'), ("&apos;", "'"), ("&#39;", "'"))

# --- Segmentation ----------------------------------------------------------------------------

_WORD_RE = re.compile(r"\S+")
# Sentence end: . ! ? (optionally followed by a closing quote/bracket), then whitespace.
_SENTENCE_BOUNDARY_RE = re.compile(r"(?<=[.!?])\s+|(?<=[.!?][)\"'\]])\s+")
_ABBREVIATIONS = {"e.g.", "i.e.", "approx.", "fig.", "no.", "ref.", "vs.", "cf.", "incl."}
# A line that starts a list item: "1.", "2)", "4.1", "a)", "-", "•".
_LIST_START_RE = re.compile(r"^(?:\d+[.)]|\d+(?:\.\d+)+\.?|[a-zA-Z][.)]|[-•*▪\u2013·])\s+")
_LIST_NUMBER_RE = re.compile(r"^\d+(?:\.\d+)*\.$")
_LIST_TOKEN_RE = re.compile(r"^(?:\d+[.)]?|\d+(?:\.\d+)+\.?|[a-zA-Z][.)]|[-•*▪\u2013·])$")
_NUMBERED_HEADING_RE = re.compile(r"^\d+(?:\.\d+)*\.?\s+[^\W\d_]")
_RISK_LABEL_RE = re.compile(r"^(?P<label>warning|caution|danger|note)\b\s*[:!\-\u2013]?\s*", re.I)
_SAFETY_LABELS = {"warning", "caution", "danger"}

# --- Heuristics ------------------------------------------------------------------------------

_NORMATIVE_RE = re.compile(r"\b(?:shall|must|should|may|required|do not|never)\b", re.I)
_OBLIGATIONS: tuple[tuple[Obligation, re.Pattern[str]], ...] = (
    ("mandatory", re.compile(r"\b(?:shall|must|required|do not|never)\b", re.I)),
    ("recommended", re.compile(r"\bshould\b", re.I)),
    ("permitted", re.compile(r"\bmay\b", re.I)),
)
_RISK_RE = re.compile(
    r"\b(?:warnings?|caution|dangerous|danger|hazards?|hazardous|injury|injuries|failures?)\b",
    re.I,
)
_HIGH_SEVERITY_RE = re.compile(
    r"\b(?:danger|dangerous|warning|injury|injuries|death|fatal|serious|burns?|crush\w*|"
    r"amputation|electric shock|explosion|fire)\b",
    re.I,
)
_MEDIUM_SEVERITY_RE = re.compile(r"\b(?:caution|hazards?|hazardous|damage)\b", re.I)
_PURPOSE_HEADING_RE = re.compile(r"\b(?:purpose|scope|objective)\b", re.I)
_PURPOSE_TEXT_RE = re.compile(
    r"\b(?:purpose|scope|this (?:procedure|document|sop|instruction)|describes|defines|"
    r"applies to|establishes)\b",
    re.I,
)
_CATEGORIES: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "Safety",
        re.compile(
            r"\b(?:safety|ppe|lockout|tagout|loto|hazard\w*|glove\w*|glasses|guards?|"
            r"injur\w*|protective)\b",
            re.I,
        ),
    ),
    ("Inspection", re.compile(r"\b(?:inspect\w*|check\w*|verif\w*|measur\w*|test\w*)\b", re.I)),
    ("Documentation", re.compile(r"\b(?:record\w*|document\w*|log\w*|sign\w*|report\w*)\b", re.I)),
    ("Training", re.compile(r"\b(?:train\w*|qualified|authori[sz]ed|competent)\b", re.I)),
    (
        "Maintenance",
        re.compile(r"\b(?:lubricat\w*|replac\w*|clean\w*|maint\w*|tighten\w*)\b", re.I),
    ),
)

_NUMBER = r"\d+(?:[.,]\d+)?"
_VALUE = rf"(?:[<>≤≥]=?\s*|±\s*)?{_NUMBER}(?:\s*(?:-|\u2013|to|±|\+/-)\s*{_NUMBER})?"
_UNITS = (
    "°C|°F|N·m|Nm|kPa|MPa|bar|psi|rpm|kW|kg|mm|cm|µm|μm|mL|ml|minutes|minute|min|seconds|second|"
    "hours|hour|days|day|weeks|week|months|month|years|year|h|s|%|t|m|g|L|Hz"
)
_SPEC_RE = re.compile(rf"(?P<value>{_VALUE})\s*(?P<unit>{_UNITS})(?![\w·])")
_PH_RE = re.compile(rf"\bpH\s*(?:of\s*|=\s*)?(?P<value>{_VALUE})")
_PARAM_WORD_RE = re.compile(r"[^\W\d_][\w'/-]*")
_PARAM_STOPWORDS = {
    "a", "about", "above", "after", "all", "an", "and", "approx", "approximately", "are", "at",
    "be", "before", "below", "between", "by", "do", "does", "each", "every", "exceed", "exceeds",
    "for", "from", "held", "in", "is", "it", "kept", "least", "less", "maintained", "max",
    "maximum", "may", "min", "minimum", "more", "must", "not", "of", "on", "or", "over", "reach",
    "reaches", "set", "shall", "should", "than", "the", "to", "under", "up", "will", "with",
    "within",
}  # fmt: skip
_ASK_STOPWORDS = {
    "a", "about", "after", "all", "also", "an", "and", "any", "are", "as", "at", "be", "before",
    "can", "could", "did", "do", "document", "does", "during", "for", "from", "has", "have",
    "how", "i", "if", "in", "is", "it", "its", "me", "much", "my", "of", "on", "or", "procedure",
    "should", "sop", "tell", "than", "that", "the", "there", "this", "to", "was", "we", "what",
    "when", "where", "which", "who", "why", "will", "with", "would", "you",
}  # fmt: skip
_ASK_TOKEN_RE = re.compile(r"[^\W_]+")

_T = TypeVar("_T")


@dataclass(frozen=True)
class _Page:
    number: int
    text: str
    no_text: bool


@dataclass(frozen=True)
class _Sentence:
    """A sentence (or heading) located by offsets in its page text."""

    page: int
    start: int
    end: int
    page_text: str = field(repr=False)
    heading: str | None
    is_heading: bool

    @property
    def text(self) -> str:
        return self.page_text[self.start : self.end]

    @property
    def clean(self) -> str:
        """Whitespace-collapsed text without a leading list marker (for display fields)."""
        collapsed = " ".join(self.text.split())
        return _LIST_START_RE.sub("", collapsed, count=1) or collapsed

    @property
    def word_count(self) -> int:
        return len(self.text.split())


class _Document:
    """The parsed pages and sentences of one request's document context."""

    def __init__(self, document_context: str) -> None:
        self.pages = _parse_pages(document_context)
        self._word_spans = {
            page.number: [m.span() for m in _WORD_RE.finditer(page.text)] for page in self.pages
        }
        self.sentences = _segment(self.pages)
        self.body = [s for s in self.sentences if not s.is_heading and s.word_count >= 3]

    @property
    def no_text_pages(self) -> list[int]:
        return [p.number for p in self.pages if p.no_text]

    def quote(self, sentence: _Sentence, focus: int | None = None) -> SourceQuote:
        """An exact substring of the page text, 5-25 words, trimmed at word boundaries.

        Long sentences are windowed around ``focus`` (a page-text offset); sentences shorter
        than five words are extended with the words that follow them on the page.
        """
        spans = self._word_spans[sentence.page]
        starts = [s for s, _ in spans]
        first = bisect.bisect_left(starts, sentence.start)
        last = bisect.bisect_right(starts, sentence.end - 1) - 1
        text = sentence.page_text
        if last - first + 1 > _MIN_QUOTE_WORDS and _LIST_TOKEN_RE.match(text[slice(*spans[first])]):
            first += 1
        count = last - first + 1
        if count < _MIN_QUOTE_WORDS:
            last = min(len(spans) - 1, first + _MIN_QUOTE_WORDS - 1)
            first = max(0, last - _MIN_QUOTE_WORDS + 1)
        elif count > _MAX_QUOTE_WORDS:
            anchor = first
            if focus is not None:
                anchor = max(first, min(last, bisect.bisect_right(starts, focus) - 1))
            first = max(first, min(anchor - 8, last - _MAX_QUOTE_WORDS + 1))
            last = first + _MAX_QUOTE_WORDS - 1
        quote = text[spans[first][0] : spans[last][1]]
        trimmed = quote.rstrip(",;:(")
        return SourceQuote(page=sentence.page, quote=trimmed or quote)


class DevFakeLLMProvider(LLMProvider):
    """DEVELOPMENT ONLY: deterministic canned output for offline UI development and e2e tests."""

    name = "fake"
    development_only = True

    def __init__(self, *, delay_seconds: float = 0.0) -> None:
        self.model = "dev-fake-1"
        self._delay_seconds = delay_seconds

    @property
    def configured(self) -> bool:
        return True

    def __repr__(self) -> str:
        return f"DevFakeLLMProvider(model={self.model!r})"

    def generate_json(self, request: LLMRequest) -> LLMResponse:
        started = time.perf_counter()
        if self._delay_seconds > 0:
            time.sleep(self._delay_seconds)
        output = self._generate(request)
        text = output.model_dump_json()
        prompt_chars = sum(
            len(part) for part in (request.system, request.document_context, request.instruction)
        )
        return LLMResponse(
            text=text,
            model=self.model,
            provider=self.name,
            finish_reason="end",
            raw_finish_reason="end",
            usage=LLMUsage(input_tokens=prompt_chars // 4, output_tokens=len(text) // 4),
            latency_ms=round((time.perf_counter() - started) * 1000),
        )

    def _generate(self, request: LLMRequest) -> BaseModel:
        doc = _Document(request.document_context)
        if request.schema_name == "summarize":
            return _summarize(doc)
        if request.schema_name == "requirements":
            requirements, notes = _requirements(doc)
            return LLMRequirementsOutput(
                requirements=requirements, limitations=_limitations(doc, notes)
            )
        if request.schema_name == "risks":
            risks, notes = _risks(doc)
            return LLMRisksOutput(risks=risks, limitations=_limitations(doc, notes))
        if request.schema_name == "ask":
            return _answer(doc, _question(request.instruction))
        raise AIRequestRejectedError("The development AI provider does not support this task.")


# --- Parsing ---------------------------------------------------------------------------------


def _unescape(text: str) -> str:
    for entity, char in _ENTITIES:
        text = text.replace(entity, char)
    return text.replace("&amp;", "&")


def _parse_pages(document_context: str) -> list[_Page]:
    pages: list[_Page] = []
    for index, match in enumerate(_PAGE_RE.finditer(document_context), start=1):
        attrs = {
            m.group(1).lower(): next(g for g in m.groups()[1:] if g is not None)
            for m in _ATTR_RE.finditer(match.group("attrs"))
        }
        number_attr = attrs.get("number", "").strip()
        number = int(number_attr) if number_attr.isdigit() else index
        if any(page.number == number for page in pages):
            continue  # malformed input: keep the first page with a given number
        text = _unescape(match.group("body") or "")
        no_text = attrs.get("status", "").lower() in _NO_TEXT_STATUSES or not text.strip()
        pages.append(_Page(number=number, text=text, no_text=no_text))
    return pages


def _question(instruction: str) -> str:
    match = _QUESTION_RE.search(instruction)
    raw = match.group("q") if match else _TAG_RE.sub(" ", instruction)
    return " ".join(_unescape(raw).split())


# --- Segmentation ----------------------------------------------------------------------------


def _is_heading(line: str) -> bool:
    words = line.split()
    if len(words) > 8 or line[-1] in ".!?;,":
        return False
    if _NORMATIVE_RE.search(line) or _RISK_LABEL_RE.match(line):
        return False
    letters = [c for c in line if c.isalpha()]
    if not letters:
        return False
    if all(c.isupper() for c in letters):
        return True
    return bool(_NUMBERED_HEADING_RE.match(line)) and len(words) <= 5


def _segment(pages: list[_Page]) -> list[_Sentence]:
    """Split pages into headings and sentences, tracking the current section heading."""
    sentences: list[_Sentence] = []
    heading: str | None = None
    for page in pages:
        if page.no_text:
            continue
        for start, end, is_heading in _segment_page(page.text):
            if is_heading:
                heading = " ".join(page.text[start:end].split())
            sentences.append(
                _Sentence(
                    page=page.number,
                    start=start,
                    end=end,
                    page_text=page.text,
                    heading=heading,
                    is_heading=is_heading,
                )
            )
    return sentences


def _segment_page(text: str) -> list[tuple[int, int, bool]]:
    """Return ``(start, end, is_heading)`` spans of headings and sentences in ``text``."""
    spans: list[tuple[int, int, bool]] = []
    block: list[int] = []  # [start, end] of the paragraph being collected

    def close_block() -> None:
        if block:
            spans.extend((s, e, False) for s, e in _split_sentences(text, block[0], block[1]))
            block.clear()

    previous_end = 0
    for match in re.finditer(r"[^\n]+", text):
        line = match.group()
        stripped = line.strip()
        blank_gap = text.count("\n", previous_end, match.start()) >= 2
        previous_end = match.end()
        if not stripped:
            close_block()
            continue
        start = match.start() + len(line) - len(line.lstrip())
        end = match.start() + len(line.rstrip())
        if _is_heading(stripped):
            close_block()
            spans.append((start, end, True))
            continue
        if blank_gap or _LIST_START_RE.match(stripped) or _RISK_LABEL_RE.match(stripped):
            close_block()
        if block:
            block[1] = end
        else:
            block.extend((start, end))
    close_block()
    return spans


def _split_sentences(text: str, start: int, end: int) -> list[tuple[int, int]]:
    chunk = text[start:end]
    pieces: list[tuple[int, int]] = []
    position = 0
    for boundary in _SENTENCE_BOUNDARY_RE.finditer(chunk):
        before = chunk[position : boundary.start()].split()
        if before and before[-1].lower() in _ABBREVIATIONS:
            continue
        # "1. Check ..." — a leading list number is not a sentence of its own.
        if len(before) == 1 and _LIST_NUMBER_RE.match(before[0]):
            continue
        pieces.append((position, boundary.start()))
        position = boundary.end()
    pieces.append((position, len(chunk)))
    return [(start + s, start + e) for s, e in pieces if chunk[s:e].strip()]


# --- Task builders ---------------------------------------------------------------------------


def _obligation(text: str) -> tuple[Obligation, re.Match[str]] | None:
    """The strongest normative keyword in ``text`` and its obligation level."""
    for obligation, pattern in _OBLIGATIONS:
        match = pattern.search(text)
        if match:
            return obligation, match
    return None


def _category(text: str) -> str | None:
    return next((name for name, pattern in _CATEGORIES if pattern.search(text)), None)


def _requirements(doc: _Document) -> tuple[list[LLMRequirement], list[str]]:
    found: list[LLMRequirement] = []
    for sentence in doc.body:
        result = _obligation(sentence.text)
        if result is None:
            continue
        obligation, match = result
        # "Failure may cause injury" describes a risk, not a permission.
        if obligation == "permitted" and _RISK_RE.search(sentence.text):
            continue
        found.append(
            LLMRequirement(
                statement=sentence.clean,
                basis="explicit",
                obligation=obligation,
                category=_category(sentence.text),
                sources=[doc.quote(sentence, sentence.start + match.start())],
            )
        )
    return _capped(found, "requirements")


def _specifications(doc: _Document) -> tuple[list[LLMSpecification], list[str]]:
    found: list[LLMSpecification] = []
    seen: set[tuple[str, str, str | None]] = set()
    for sentence in doc.body:
        text = sentence.text
        previous_end = 0
        parameter = ""
        matches = [(m, m.group("unit")) for m in _SPEC_RE.finditer(text)]
        matches += [(m, "pH") for m in _PH_RE.finditer(text)]
        for match, unit in sorted(matches, key=lambda item: item[0].start()):
            parameter = _parameter(text, previous_end, match.start()) or parameter
            previous_end = match.end()
            name = parameter or _first_words(sentence.clean, 4)
            value = match.group("value").strip()
            key = (name.lower(), value, unit)
            if key in seen:
                continue
            seen.add(key)
            found.append(
                LLMSpecification(
                    parameter=name,
                    value=value,
                    unit=unit,
                    context=sentence.heading,
                    sources=[doc.quote(sentence, sentence.start + match.start())],
                )
            )
    return _capped(found, "specifications")


def _parameter(text: str, lower: int, upper: int) -> str:
    """The words naming a value, e.g. 'Hydraulic oil temperature' in '... shall be 40-60 °C'."""
    segment = text[lower:upper]
    cut = max(segment.rfind(c) for c in ",;:(")
    words = _PARAM_WORD_RE.findall(segment[cut + 1 :])
    while words and words[-1].lower() in _PARAM_STOPWORDS:
        words.pop()
    words = words[-4:]
    while words and words[0].lower() in _PARAM_STOPWORDS:
        words.pop(0)
    phrase = " ".join(words)
    return phrase[:1].upper() + phrase[1:]


def _risks(doc: _Document) -> tuple[list[LLMRisk], list[str]]:
    found: list[LLMRisk] = []
    for sentence in doc.body:
        match = _RISK_RE.search(sentence.text)
        if match is None:
            continue
        found.append(
            LLMRisk(
                title=_risk_title(sentence),
                description=sentence.clean,
                severity=_severity(sentence.text),
                basis="explicit",
                sources=[doc.quote(sentence, sentence.start + match.start())],
            )
        )
    return _capped(found, "risks")


def _severity(text: str) -> Severity:
    if _HIGH_SEVERITY_RE.search(text):
        return "high"
    if _MEDIUM_SEVERITY_RE.search(text):
        return "medium"
    return "low"


def _risk_title(sentence: _Sentence) -> str:
    text = sentence.clean
    label = _RISK_LABEL_RE.match(text)
    if label and label.group("label").lower() in _SAFETY_LABELS:
        rest = _first_words(text[label.end() :], 7)
        return f"{label.group('label').capitalize()}: {rest}" if rest else text
    return _first_words(text, 8)


def _actions(risks: list[LLMRisk]) -> list[LLMAction]:
    """Two or three generic, inferred actions derived from the risks that were found."""
    if not risks:
        return []
    high = [r for r in risks if r.severity == "high"]
    actions: list[LLMAction] = []
    if high:
        actions.append(
            LLMAction(
                action=(
                    "Confirm that everyone performing this procedure is trained on the "
                    "high-severity hazards it identifies."
                ),
                rationale=(
                    f"The document names {len(high)} high-severity risk statement(s), "
                    f"for example: {high[0].title}."
                ),
                priority="high",
                basis="inferred",
                sources=list(high[0].sources),
            )
        )
    actions.append(
        LLMAction(
            action="Check that the warnings and cautions in this document are visible at the "
            "point of use.",
            rationale=f"The document contains {len(risks)} risk-related statement(s).",
            priority="medium",
            basis="inferred",
            sources=list(risks[0].sources),
        )
    )
    if len(risks) > 1:
        actions.append(
            LLMAction(
                action="Review the identified risks with the document owner at the next "
                "periodic review.",
                rationale=f"Risks are described in several places, for example: {risks[-1].title}.",
                priority="low",
                basis="inferred",
                sources=list(risks[-1].sources),
            )
        )
    return actions


def _summarize(doc: _Document) -> LLMSummarizeOutput:
    requirements, req_notes = _requirements(doc)
    specifications, spec_notes = _specifications(doc)
    risks, risk_notes = _risks(doc)
    limitations = _limitations(doc, req_notes + spec_notes + risk_notes)

    candidates = [s for s in doc.body if s.word_count >= _MIN_QUOTE_WORDS]
    if not candidates:
        summary = LLMSummary(
            purpose="The document contains no extractable text to summarize.",
            executive=LLMExecutiveSummary(
                text="No text could be analyzed, so no summary was produced. "
                "Review the source document directly.",
                sources=[],
            ),
            key_points=[],
        )
        return LLMSummarizeOutput(
            summary=summary,
            requirements=[],
            specifications=[],
            risks=[],
            actions=[],
            limitations=limitations,
        )

    intro = _intro(candidates)
    purpose = intro[0]

    mandatory = sum(1 for r in requirements if r.obligation == "mandatory")
    overview = (
        f"The document contains {len(requirements)} requirement statement(s) "
        f"({mandatory} mandatory), {len(specifications)} specified value(s) and "
        f"{len(risks)} risk-related statement(s)."
    )
    executive = LLMExecutiveSummary(
        text=" ".join([*(_as_sentence(s.clean) for s in intro), overview]),
        sources=[doc.quote(s) for s in intro],
    )
    summary = LLMSummary(
        purpose=purpose.clean,
        executive=executive,
        key_points=_key_points(doc, requirements, risks, exclude=intro),
    )
    return LLMSummarizeOutput(
        summary=summary,
        requirements=requirements,
        specifications=specifications,
        risks=risks,
        actions=_actions(risks),
        limitations=limitations,
    )


def _intro(candidates: list[_Sentence]) -> list[_Sentence]:
    """Purpose (and scope) sentences from the first page with text; else its first sentence."""
    first_page = candidates[0].page
    purposeful = [
        s
        for s in candidates
        if s.page == first_page
        and (
            _PURPOSE_TEXT_RE.search(s.text)
            or (s.heading is not None and _PURPOSE_HEADING_RE.search(s.heading))
        )
    ]
    return purposeful[:2] or [candidates[0]]


def _key_points(
    doc: _Document,
    requirements: list[LLMRequirement],
    risks: list[LLMRisk],
    *,
    exclude: list[_Sentence],
) -> list[LLMKeyPoint]:
    points: list[LLMKeyPoint] = []
    seen = {s.clean for s in exclude}
    mandatory = [r for r in requirements if r.obligation == "mandatory"]
    ranked = sorted(risks, key=lambda r: ("high", "medium", "low").index(r.severity))
    for text, sources in [
        *((r.statement, r.sources) for r in mandatory[:3]),
        *((r.description, r.sources) for r in ranked[:2]),
    ]:
        if text not in seen and len(points) < _MAX_KEY_POINTS:
            seen.add(text)
            points.append(LLMKeyPoint(text=text, sources=list(sources)))
    for sentence in doc.body:
        if len(points) >= 3:
            break
        if sentence.word_count >= _MIN_QUOTE_WORDS and sentence.clean not in seen:
            seen.add(sentence.clean)
            points.append(LLMKeyPoint(text=sentence.clean, sources=[doc.quote(sentence)]))
    return points


def _answer(doc: _Document, question: str) -> LLMAnswerOutput:
    keywords = {_normalize(t) for t in _ASK_TOKEN_RE.findall(question.lower())}
    keywords = {k for k in keywords if len(k) >= 3 and k not in _ASK_STOPWORDS}

    scored: list[tuple[int, int, _Sentence, int]] = []
    for order, sentence in enumerate(doc.body):
        tokens = list(_ASK_TOKEN_RE.finditer(sentence.text))
        hits = [t for t in tokens if _normalize(t.group().lower()) in keywords]
        overlap = len({_normalize(t.group().lower()) for t in hits})
        if overlap:
            scored.append((-overlap, order, sentence, sentence.start + hits[0].start()))
    scored.sort(key=lambda item: (item[0], item[1]))

    if not scored:
        candidates = [s for s in doc.body if s.word_count >= _MIN_QUOTE_WORDS]
        answer = "The document does not appear to contain information about this question."
        if candidates:
            answer += f" It covers: {_as_sentence(_intro(candidates)[0].clean)}"
        return LLMAnswerOutput(answerable=False, answer=answer, sources=[])

    best = -scored[0][0]
    chosen = [item for item in scored[:2] if -item[0] * 2 >= best]
    chosen.sort(key=lambda item: item[1])  # document order
    return LLMAnswerOutput(
        answerable=True,
        answer="According to the document: " + " ".join(item[2].clean for item in chosen),
        sources=[doc.quote(item[2], item[3]) for item in chosen],
    )


# --- Helpers ---------------------------------------------------------------------------------


def _normalize(token: str) -> str:
    return token[:-1] if len(token) > 3 and token.endswith("s") else token


def _as_sentence(text: str) -> str:
    return text if text.endswith((".", "!", "?")) else f"{text}."


def _first_words(text: str, count: int) -> str:
    return " ".join(text.split()[:count]).rstrip(".,;:!?")


def _capped(items: list[_T], label: str) -> tuple[list[_T], list[str]]:
    if len(items) <= MAX_ITEMS:
        return items, []
    return items[:MAX_ITEMS], [
        f"Only the first {MAX_ITEMS} of {len(items)} {label} found are listed."
    ]


def _limitations(doc: _Document, notes: list[str]) -> list[str]:
    limitations = [_DEV_LIMITATION]
    if not doc.pages:
        limitations.append("No page content was provided.")
    elif doc.no_text_pages:
        pages = ", ".join(str(n) for n in doc.no_text_pages)
        limitations.append(f"Page(s) {pages} had no extractable text and were not analyzed.")
    limitations.extend(notes)
    return limitations
