"""Mock Windchill document provider.

DEVELOPMENT ONLY. This provider is NOT connected to Windchill. It serves a small catalog of
synthetic SOP documents from the local ``samples`` directory so the platform can be developed
and demonstrated without a Windchill system:

* ``samples/catalog.json`` holds Windchill-like metadata (camelCase ``DocumentMetadata``) and
  the file name of each document's PDF.
* The PDFs next to the catalog are generated by ``scripts/generate_samples.py``.

Every document it returns is flagged ``development_only`` so the UI can say so. It performs no
authorization: the real provider must authorize the requester (see ``base.py``).
"""

from __future__ import annotations

import json
import logging
import re
import threading
from dataclasses import dataclass
from pathlib import Path

from pydantic import BaseModel, ConfigDict, ValidationError

from docintel.core.errors import (
    ContentNotAvailableError,
    DocumentNotFoundError,
    WindchillProviderError,
)
from docintel.core.models import DocumentMetadata, Requester
from docintel.providers.windchill.base import (
    ContentDescriptor,
    DocumentContent,
    WindchillDocument,
    WindchillDocumentProvider,
)

logger = logging.getLogger(__name__)

CATALOG_FILENAME = "catalog.json"
PDF_MEDIA_TYPE = "application/pdf"

# A catalog entry may only name a plain PDF file directly inside the samples directory: no path
# separators, no leading dot (so no "." / ".." / hidden files), no control characters.
_SAFE_FILENAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._ -]{0,195}\.pdf$", re.IGNORECASE)


class _CatalogEntry(BaseModel):
    model_config = ConfigDict(extra="ignore")

    reference: str
    file: str
    metadata: DocumentMetadata


@dataclass(frozen=True)
class _Document:
    reference: str
    filename: str
    path: Path
    metadata: DocumentMetadata


class MockWindchillDocumentProvider(WindchillDocumentProvider):
    """DEVELOPMENT ONLY document source backed by ``<samples_dir>/catalog.json``."""

    name = "mock-windchill"
    development_only = True

    def __init__(self, samples_dir: Path) -> None:
        self._dir = Path(samples_dir)
        self._documents: dict[str, _Document] | None = None
        self._lock = threading.Lock()

    # --- WindchillDocumentProvider ---------------------------------------------------------

    def list_documents(
        self, *, requester: Requester, query: str | None = None, limit: int = 50
    ) -> list[WindchillDocument]:
        """Catalog documents whose number, name or location contains ``query`` (any case)."""
        needle = (query or "").strip().casefold()
        matches = [
            doc for doc in self._catalog().values() if not needle or _matches(doc.metadata, needle)
        ]
        return [self._describe(doc) for doc in matches[: max(limit, 0)]]

    def get_document(self, reference: str, *, requester: Requester) -> WindchillDocument:
        return self._describe(self._lookup(reference))

    def get_primary_content(self, reference: str, *, requester: Requester) -> DocumentContent:
        doc = self._lookup(reference)
        try:
            data = doc.path.read_bytes()
        except FileNotFoundError:
            raise ContentNotAvailableError(
                "The sample PDF for this development document is missing. "
                "Run scripts/generate_samples.py to generate the sample documents."
            ) from None
        except OSError:
            raise ContentNotAvailableError(
                "The sample PDF for this development document could not be read."
            ) from None
        return DocumentContent(filename=doc.filename, media_type=PDF_MEDIA_TYPE, data=data)

    # --- internals -------------------------------------------------------------------------

    def _lookup(self, reference: str) -> _Document:
        doc = self._catalog().get(reference)
        if doc is None:
            raise DocumentNotFoundError()
        return doc

    def _describe(self, doc: _Document) -> WindchillDocument:
        try:
            size: int | None = doc.path.stat().st_size if doc.path.is_file() else None
        except OSError:
            size = None
        return WindchillDocument(
            reference=doc.reference,
            metadata=doc.metadata.model_copy(),
            primary_content=ContentDescriptor(
                filename=doc.filename, media_type=PDF_MEDIA_TYPE, size_bytes=size
            ),
            development_only=True,
        )

    def _catalog(self) -> dict[str, _Document]:
        """The parsed catalog, loaded on first use and then cached."""
        with self._lock:
            if self._documents is None:
                self._documents = self._load_catalog()
            return self._documents

    def _load_catalog(self) -> dict[str, _Document]:
        try:
            raw = json.loads((self._dir / CATALOG_FILENAME).read_bytes())
            entries = raw["documents"]
            if not isinstance(entries, list):
                raise TypeError("'documents' must be a list")
        except (OSError, ValueError, KeyError, TypeError) as exc:
            logger.error("Mock Windchill catalog could not be loaded (%s)", type(exc).__name__)
            raise WindchillProviderError(
                "The development sample catalog (samples/catalog.json) could not be read."
            ) from None

        root = self._dir.resolve()
        documents: dict[str, _Document] = {}
        for index, item in enumerate(entries):
            try:
                entry = _CatalogEntry.model_validate(item)
            except ValidationError:
                logger.warning("Mock Windchill catalog entry %d is invalid; skipped", index)
                continue
            path = _safe_path(root, entry.file)
            if path is None:
                logger.warning("Mock Windchill catalog entry %d has an unsafe file name", index)
                continue
            if entry.reference in documents:
                logger.warning("Mock Windchill catalog entry %d duplicates a reference", index)
                continue
            documents[entry.reference] = _Document(
                reference=entry.reference, filename=entry.file, path=path, metadata=entry.metadata
            )
        return documents


def _safe_path(root: Path, filename: str) -> Path | None:
    """Path of ``filename`` inside ``root``, or ``None`` if the name could escape it."""
    if not _SAFE_FILENAME_RE.fullmatch(filename):
        return None
    path = (root / filename).resolve()
    # Defense in depth: a symlink in the samples directory must not point outside of it.
    return path if path.parent == root else None


def _matches(metadata: DocumentMetadata, needle: str) -> bool:
    fields = (metadata.number, metadata.name, metadata.location)
    return any(needle in value.casefold() for value in fields if value)
